services:
  postgres:
    image: postgres:16-alpine
    container_name: uishop_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: randompassword
      POSTGRES_DB: uishop_db
    ports:
      - "5432:5432"
    volumes:
      # Volumen local con persistencia — la carpeta se crea automáticamente
      - ./docker-data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d uishop_db"]
      interval: 10s
      timeout: 5s
      retries: 5
